apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secret-rotation
  namespace: monitoring
  labels:
    app: secret-rotation
spec:
  selector:
    matchLabels:
      app: secret-rotation
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: secret-rotation-alerts
  namespace: monitoring
spec:
  groups:
    - name: secret-rotation
      rules:
        - alert: SecretRotationFailed
          expr: secret_rotation_errors_total > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Secret rotation failed
            description: "Secret rotation has failed for {{ $labels.platform }}"

        - alert: SecretRotationStale
          expr: time() - secret_rotation_last_success_timestamp > 7776000  # 90 days
          for: 1h
          labels:
            severity: warning
          annotations:
            summary: Secrets are stale
            description: "Secrets haven't been rotated in 90 days for {{ $labels.platform }}"

        - alert: SecretRotationDurationHigh
          expr: secret_rotation_duration_seconds > 300  # 5 minutes
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Secret rotation taking too long
            description: "Secret rotation is taking longer than 5 minutes for {{ $labels.platform }}"

        - alert: SecretRotationRateHigh
          expr: rate(secret_rotation_total[1h]) > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High secret rotation rate
            description: "Secrets are being rotated more than once per hour for {{ $labels.platform }}"

        - alert: SecretBackupFailed
          expr: secret_backup_errors_total > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Secret backup failed
            description: "Failed to create backup for {{ $labels.platform }}"

        - alert: SecretEncryptionFailed
          expr: secret_encryption_errors_total > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Secret encryption failed
            description: "Failed to encrypt secrets for {{ $labels.platform }}"

        - alert: SecretAccessDenied
          expr: secret_access_denied_total > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Secret access denied
            description: "Access to secrets was denied for {{ $labels.platform }}"

        - alert: SecretAuditLogFailed
          expr: secret_audit_log_errors_total > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Secret audit logging failed
            description: "Failed to log secret access for {{ $labels.platform }}"

        - alert: SecretValidationFailed
          expr: secret_validation_errors_total > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Secret validation failed
            description: "Secret validation failed for {{ $labels.platform }}"

        - alert: SecretComplexityLow
          expr: secret_complexity_score < 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Low secret complexity
            description: "Secret complexity is below threshold for {{ $labels.platform }}"

        - alert: SecretReuseDetected
          expr: secret_reuse_detected_total > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Secret reuse detected
            description: "Secret reuse detected for {{ $labels.platform }}"

        - alert: SecretExposureDetected
          expr: secret_exposure_detected_total > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Secret exposure detected
            description: "Secret exposure detected for {{ $labels.platform }}"

        - alert: SecretRotationQuotaExceeded
          expr: secret_rotation_quota_exceeded_total > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Secret rotation quota exceeded
            description: "Secret rotation quota exceeded for {{ $labels.platform }}"

        - alert: SecretBackupSizeHigh
          expr: secret_backup_size_bytes > 1e9  # 1GB
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Large secret backup size
            description: "Secret backup size is above 1GB for {{ $labels.platform }}"

        - alert: SecretRotationConcurrencyHigh
          expr: secret_rotation_concurrent_operations > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High secret rotation concurrency
            description: "Too many concurrent secret rotations for {{ $labels.platform }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-rotation-metrics
  namespace: monitoring
data:
  metrics.yaml: |
    metrics:
      - name: secret_rotation_total
        type: counter
        help: Total number of secret rotations
        labels: [platform, environment]

      - name: secret_rotation_errors_total
        type: counter
        help: Total number of secret rotation errors
        labels: [platform, environment, error_type]

      - name: secret_rotation_duration_seconds
        type: histogram
        help: Duration of secret rotations
        labels: [platform, environment]
        buckets: [30, 60, 120, 300, 600]

      - name: secret_rotation_last_success_timestamp
        type: gauge
        help: Timestamp of last successful rotation
        labels: [platform, environment]

      - name: secret_backup_errors_total
        type: counter
        help: Total number of backup errors
        labels: [platform, environment, error_type]

      - name: secret_encryption_errors_total
        type: counter
        help: Total number of encryption errors
        labels: [platform, environment, error_type]

      - name: secret_access_denied_total
        type: counter
        help: Total number of access denied errors
        labels: [platform, environment, user, reason]

      - name: secret_audit_log_errors_total
        type: counter
        help: Total number of audit log errors
        labels: [platform, environment, error_type]

      - name: secret_validation_errors_total
        type: counter
        help: Total number of validation errors
        labels: [platform, environment, error_type]

      - name: secret_complexity_score
        type: gauge
        help: Secret complexity score (0-1)
        labels: [platform, environment]

      - name: secret_reuse_detected_total
        type: counter
        help: Total number of secret reuse detections
        labels: [platform, environment, user]

      - name: secret_exposure_detected_total
        type: counter
        help: Total number of secret exposure detections
        labels: [platform, environment, exposure_type]

      - name: secret_rotation_quota_exceeded_total
        type: counter
        help: Total number of quota exceeded errors
        labels: [platform, environment]

      - name: secret_backup_size_bytes
        type: gauge
        help: Size of secret backups in bytes
        labels: [platform, environment]

      - name: secret_rotation_concurrent_operations
        type: gauge
        help: Number of concurrent rotation operations
        labels: [platform, environment]

      - name: secret_rotation_success_rate
        type: gauge
        help: Success rate of secret rotations
        labels: [platform, environment]

      - name: secret_rotation_latency_seconds
        type: histogram
        help: Latency of secret rotation operations
        labels: [platform, environment]
        buckets: [0.1, 0.5, 1, 2, 5]

      - name: secret_backup_retention_days
        type: gauge
        help: Number of days backups are retained
        labels: [platform, environment]

      - name: secret_rotation_attempts_total
        type: counter
        help: Total number of rotation attempts
        labels: [platform, environment, status]

      - name: secret_rotation_rollback_total
        type: counter
        help: Total number of rotation rollbacks
        labels: [platform, environment, reason]

      - name: secret_rotation_notification_sent_total
        type: counter
        help: Total number of rotation notifications sent
        labels: [platform, environment, notification_type]

      - name: secret_rotation_manual_intervention_total
        type: counter
        help: Total number of manual interventions required
        labels: [platform, environment, reason]

      - name: secret_rotation_automation_score
        type: gauge
        help: Score of automation success (0-1)
        labels: [platform, environment] 