apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
type: Opaque
data:
  # These values will be base64 encoded by the setup script
  ES_USER: ZWxhc3RpYw==  # elastic
  ES_PASSWORD: <base64-encoded-password>
  KIBANA_USER: a2liYW5h  # kibana
  KIBANA_PASSWORD: <base64-encoded-password>
  NEW_RELIC_LICENSE_KEY: <base64-encoded-key>
  DD_API_KEY: <base64-encoded-key>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring
data:
  ELASTICSEARCH_SSL_VERIFICATION: "true"
  KIBANA_SSL_VERIFICATION: "true"
  LOGSTASH_SSL_VERIFICATION: "true"
  ELASTICSEARCH_PORT: "9200"
  KIBANA_PORT: "5601"
  LOGSTASH_PORT: "5044"
  PROMETHEUS_PORT: "9090"
  JAEGER_PORT: "16686"
  ELASTICSEARCH_RETENTION_DAYS: "30"
  PROMETHEUS_RETENTION_DAYS: "15"
  JAEGER_RETENTION_DAYS: "7"
  ENABLE_APM: "true"
  ENABLE_LOGGING: "true"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true" 