name: Performance Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './lighthouse.config.js'

      - name: Run k6 Performance Tests
        uses: grafana/k6-action@v0.2.0
        with:
          filename: performance-tests/load-test.js

      - name: Run WebPageTest
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.request({
              method: 'POST',
              url: 'https://www.webpagetest.org/runtest.php',
              data: {
                url: process.env.APP_URL,
                k: process.env.WPT_API_KEY,
                runs: 3,
                fvonly: 1
              }
            });
            console.log(response.data);

      - name: Upload Performance Report
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: |
            .lighthouseci/
            k6-summary.json
          retention-days: 7 