name: Test Secrets Management

on:
  push:
    paths:
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/test-secrets.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/test-secrets.yml'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [k8s, aws, azure, gcp, local]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Set up test environment
        run: |
          mkdir -p k8s/secrets/backup
          touch k8s/secrets/audit.log
          chmod 600 k8s/secrets/audit.log

      - name: Set up platform-specific tools
        run: |
          case ${{ matrix.platform }} in
            k8s)
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              sudo mv kubectl /usr/local/bin/
              ;;
            aws)
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              ;;
            azure)
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              ;;
            gcp)
              echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
              curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
              sudo apt-get update && sudo apt-get install google-cloud-sdk
              ;;
          esac

      - name: Set up test secrets
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          chmod +x tests/test-secrets.sh
          ./tests/test-secrets.sh

      - name: Run tests
        run: |
          ./tests/test-secrets.sh

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.platform }}
          path: |
            k8s/secrets/audit.log
            k8s/secrets/backup/*

      - name: Notify on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'monitoring'
          slack-message: "❌ Secret management tests failed for platform: ${{ matrix.platform }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 